piVersion: v1
kind: Service
metadata:
  name: roles
spec:
  selector:
    app: roles
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roles
spec:
  selector:
    matchLabels:
      app: roles
  replicas: 1
  template:
    metadata:
      labels:
        app: roles
    spec:
      containers:
        - name: server
          image: blindfaith/role-service:latest
          ports:
            - name: http
              containerPort: 8081

